language: node_js
node_js:
  - 11

cache:
  npm: true

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "aFzCfGRMF9aDQEofSn2x9+9a9qKPZSman/4q51ZDm2izt1thuH9d03BoqTFnXXIcs51aqDrh8LjqfNpKfB5svWHbCW3wYbVlo9m8WTDrVoaluIIlgzQcWn2i3RbOfqDU/AweowlCEcBwF/B1vdNjwyC92CiRSea1jEzfRp4/CpI5+8wLbyPc4tIa0X4LPE9p3dtuMcIGYC0UemH8PXjPthnI7i1fsFYvSdMdpsvpJeRdklTZjl9W2STOCfNIfHsF81Ey+TZdOZSHK7IIZF9E2Uz3hsF4O2AbfTCtBNTp+JlLjRwZnH/JWStl/JK/MvZ2++KhSCtnACLBUHVEhpqr9G/4/kCIxCmIat1jU5pJW6tQPvYZvnF0KcVKxiBof6fMcWbd3hxqiKP1ymaSXxomnA8DB72gPYRgoA+Fz0AJazz3rh1MGRwwVH8H/QHq1sRW4vcYjYC2LDzmPOGd0cwFpLuG974oglIluVJXL8Su+dooeibJq81nfN3lDzn5Txlv2uZPj5o0Ca/rTIz/yYdZZ3QAN59vW04btzNJWYg1lzxu+SgNhwoVnCOpCnFHo5WmL2VJbJFybpWj/0820SZ/B31omaccZAal/v6gxBsM2bPqGT6FB+RDDxv+m9wbrraQfNUSLaBNJiDwhTZnFjdunlR8G9tDaPwmccyAnj5dIpU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Ocm33hxZWAnZtdSOSMVrJEZ2anHU1sNrwSAKJe3WuRozS5UZdVLa9W7nLfuvZtBoLZz6ZfKTQZ3di8opcmsWFjpdhNoBMKNiYSPLB3VFEr4kvSHa1Tyo2L7ESSkW74pxLlj7E7z/QJzFfRcCVkkuxGXHbPJt4XibG+ZEKE9F8MmF1V4YYQJ4gPhJHha+FPHTiZH+E/AQXKseGOn9bIRVxD0RJbqjcXY/bmMxLX6z5Cao+zP12USMJlBw7aTN5v/T4lLiXlHgTOuNipvv3rEHckMNBm0WKMwVDYdmRpkF6Ro/upebu1o+4xSP6bckO/FzzTsa9t0IT9pdNj2WMMiUHGI4jx/wvso99xpQ+E6+nQCaiIjXWbaORY9LYtK6PShhNiGTzYrO6e9D+f+8O64WpK52ZjtztmT7QfXa9cqRMpmX2iYXGwkU1asvPbE//+kdxWwU00FjXWXLR5l6PWmzXPV5ZJQoRE1yDq+U811evMh5PqxlQLokhtB6risDlwEzmz0DllVp6+er7huBWqx773ieI8CkChvTPvRc/++xMMbDQfxLUQT3cg7ukuGxgV8Fsd1/YQCGF4DTqlmd92NkC9+E1VHO6xh92bAdDwlDjgaPbemdtMreoSURjHzmBc5Uy4NZNzYBWZKmye1BkYODZQcnpe6pvUKmcAr1+G9VuiI="
    # NPM_TOKEN
    - secure: "WfQ+res2kbIHyGZLNs6eU/ZTg4a3AStDz6goqOziUgtxiFKIcnF6xoP8r+xxhqjnq4QEX1hpRzoRe+EGMiCxeZmIMW4IfiN1SZ7eSnRF6EiCTlsuXQi5zfVwomBdw+WmkqZTc7WuljVnrpn7hzXdIWXnwrwtn3HkgtUKQ9N6XuzT1mICihqeJTrAukgCoTg6p+lHMf8iOYfLeIMHO4ruf5Fn+BaoOC7Zi5Utq3JbFmVfDceJjdhR85D29D5cjk2X+eXlCo6fl/i1WUsI4ZCHMSZAARJtgbdra/PnMoyI81xGA32XfS9wRxHZsXXEy5zi9icgCUX5qBuj6GTo9zQx8j4LD9EN3lODVwULj4TS5QLMDDoz0hgg+ItPuDni30VKn0NrKGNScVkW5igiqPXIETxYTPPyI8VV0IVUWNbTlj5loDyvGRKvrVerhQWmTNZs6KvG6g6jNemQTUNmWeEQIR9AdrE3FhzPVMUe6HqJxzE6ZpZ2FeE7RNkRlnzuwyqhjsdEXWJ7NuAzWhdJ4F4nlBjUTCKtMWlAvz//H/Z5dCEWbNxJF24ui2CG+N7s4ZJzNPhumVE3PmrSZxMxMoXaCiNoiQSdwol698HH/gsBLzVk9Jt3G2bJ8O3F2exOujnIXMZBU1JZrE+rcpLU367ao6PlJbDVcxBKyB3i3Pn2Rtc="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - npm install

script:
  - sh scripts/build.sh
  - sh scripts/build-storybook.sh

deploy:
  - provider: script
    script: sh scripts/publish.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: sh scripts/deploy-storybook.sh
    skip_cleanup: true
    on:
      all_branches: true