language: node_js
node_js:
  - 11

cache:
  npm: true

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "g2OM4+7mpAyfv2c6j67aFl8xQL/fFkd9H5+5uybBCtC6D1ogwnPjf4iRrKg7/4CznOprTMcpYZJVevYtyGns44W+jyiFFagpfebcgjb8q2Qf3IwzxCKoHiIRXWsZ7WlJaljIwzJ34pFTujJS+bO7HTfAf12pTlMvC3rqoXsDF0rj+74fXA3sZDx2pXFJcLsQH52ipnR/1a8QuGZgkItdlH9lUtOtGOh2qN2RU09XSmN1eU3B4ntKqDcjjoapt9mMw9O0hyNrN6CpYl9zPDseScyzUdLiFppsy7JfjFve9FLubSAHthn1U5WLTs+pM/Z5u3I67v7NQ914nYInJydC4ZD0XYSqFpFlCaHc1UopR8w6RDTnvDScV2t3dgKKPGqaVavWgVSviM+9Qp61LRh0Ffrbd970DQNu2neaOjelspQ+MQ1Tj32XCVux1/rweIHH8POTnd24iEpeK3akpPz6FIIv6qjC0xbRD4UDElLc8Lj/5NbUPYo8FCNo/yQWqiLJNmfevQWEr//yrsLOB/Y9LjKl+qMOK4rXBlyMPmyUGXVKWVPfqeRkZ5kZakHu1kt/WOrWhIv/+IRu8L63t4W3TkUaN1z/ESl445lkD9GaSAlSADeTxw/hcxyLh9/JRi8b5GF79pUZ5r2gEHgFCw7Vk9nKWxK76I7LqO3oJ7dDI98="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Rc81nHZO6Rcsk94NNAAw2LfEQ93xLW61lYEEfQ0J98RAsYHVkFFtn2I9f/1db2ZkxTSzYYosVr6leXpHWRNWmm2y8J32g9MLngoKFYpZZRiVZpgdkI1eENAjmt2wfmWm9zPEggH4LxrNzK1okrtnZKWyiJAw6aCEaxGJQ1VyXDtWqgokC9L+Z5MSpgvDfwpJfdlWuFs9zvE03x3lKCKoVGPjLlhcTFXiJFFIKCN7GshB4bsFQHeUNf11J+Qy5fuiscpOtY1PHTIRJZiOVNbZ9ZbNGESL+xM0rWWGiXEtyI06iXKkVBPP0jHTjaVDC6Nz7qVraHNhVGN6c7TdvCDEMtxemNWVAUvK4AjpVEsgJOnoMTXL0wOpWkl41VKX5OoWxa/s1ZAXHjTuuI6OJX+Tcr119MRzUpq78YoBvy9gsXBsmdAnJJ5WQ5o7nrYOO+vmoXnGx6fwWMw4CeUV0YpMABK32YKvqrryge3nDahjfXps47dEjMn0w6rklWZnacrlq8N6l3OdLIEKBfSVwe/7C+R8Oq3u2yfSos4ackq+pSk6XM2Wu9jG72doo6Giys3zp12srhWzmBcgnaNqld0HlNQBskfFIaWJi3CmZFAG5RKLqcBx3zYjRZB4Wu8D2Y98E1DZz9WZ4oB8d9HN0mwxvPQs5aMn9uvp9PsvDdncFkA="
    # NPM_TOKEN
    - secure: "WfQ+res2kbIHyGZLNs6eU/ZTg4a3AStDz6goqOziUgtxiFKIcnF6xoP8r+xxhqjnq4QEX1hpRzoRe+EGMiCxeZmIMW4IfiN1SZ7eSnRF6EiCTlsuXQi5zfVwomBdw+WmkqZTc7WuljVnrpn7hzXdIWXnwrwtn3HkgtUKQ9N6XuzT1mICihqeJTrAukgCoTg6p+lHMf8iOYfLeIMHO4ruf5Fn+BaoOC7Zi5Utq3JbFmVfDceJjdhR85D29D5cjk2X+eXlCo6fl/i1WUsI4ZCHMSZAARJtgbdra/PnMoyI81xGA32XfS9wRxHZsXXEy5zi9icgCUX5qBuj6GTo9zQx8j4LD9EN3lODVwULj4TS5QLMDDoz0hgg+ItPuDni30VKn0NrKGNScVkW5igiqPXIETxYTPPyI8VV0IVUWNbTlj5loDyvGRKvrVerhQWmTNZs6KvG6g6jNemQTUNmWeEQIR9AdrE3FhzPVMUe6HqJxzE6ZpZ2FeE7RNkRlnzuwyqhjsdEXWJ7NuAzWhdJ4F4nlBjUTCKtMWlAvz//H/Z5dCEWbNxJF24ui2CG+N7s4ZJzNPhumVE3PmrSZxMxMoXaCiNoiQSdwol698HH/gsBLzVk9Jt3G2bJ8O3F2exOujnIXMZBU1JZrE+rcpLU367ao6PlJbDVcxBKyB3i3Pn2Rtc="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - npm install

script:
  - sh scripts/build.sh
  - sh scripts/build-storybook.sh

deploy:
  - provider: script
    script: sh scripts/publish.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: sh scripts/deploy-storybook.sh
    skip_cleanup: true
    on:
      all_branches: true