name: virkailija-ui-components

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      - name: Run tests
        run: |
          npm run lint
          npm run test

      - name: Publish storybook
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          npm run build-storybook
          sh scripts/deploy-storybook.sh

      - name: Build and Publish package
        if: github.ref == 'refs/heads/master'
        run: |
          npm run build
          sh scripts/publish.sh
