name: virkailija-ui-components

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit --prefer-offline --ignore-scripts
          npm rebuild canvas

      - name: Run tests
        run: |
          npm run lint
          npm run test

      - name: Publish storybook
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          npm run build-storybook
          sh scripts/deploy-storybook.sh

      - name: Build and Publish package
        if: github.ref == 'refs/heads/master'
        run: |
          npm run build
          sh scripts/publish.sh
